spring:
  rabbitmq:
    host: rabbitmq.loans.svc.cluster.local

email:
  host: maildev.loans.svc.cluster.local

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key