server:
  port: 8081

logging:
  file:
    name: logs/risk-checker.log

spring:
  output:
    ansi:
      enabled: ALWAYS
  web:
    error:
      include-message: always
      include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true

application:
  timeZone: Europe/Vilnius
  loanLimitPerDay: 30
  maxAmount: 100
  forbiddenHourFrom: 0
  forbiddenHourTo: 6

---
spring:
  config:
    activate:
      on-profile: docker,k8s

logging:
  file:
    name: ""
  structured:
    format:
      console: logstash
    json:
      rename:
        logger_name: class
      add:
        hostname: ${HOSTNAME:}
        app: ${spring.application.name}
        profiles: ${spring.profiles.active:}
