server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:h2:/home/osvaldas/Java_projects/4finance-task/build/h2db/db/interest;AUTO_SERVER=TRUE
    username: username
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      #      javax:
      #        persistence:
      #          schema-generation:
      #            create-source: metadata
      #            scripts:
      #              action: create
      #              create-target: create.sql
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

application:
  maxAmount: 100
  interestRate: 10
  interestIncrementFactor: 1.5
  postponeDays: 7
  requestsFromSameIpLimit: 3
  forbiddenHourFrom: 0
  forbiddenHourTo: 6