server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loans
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      #      javax:
      #        persistence:
      #          schema-generation:
      #            create-source: metadata
      #            scripts:
      #              action: create
      #              create-target: create.sql
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL81Dialect

application:
  maxAmount: 100
  interestRate: 10
  interestIncrementFactor: 1.5
  postponeDays: 7
  requestsFromSameIpLimit: 3
  forbiddenHourFrom: 0
  forbiddenHourTo: 6