version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      spring:
        patterns:
          - "org.springframework*"
          - "io.spring*"
          - "org.springdoc*"
      build-tooling:
        patterns:
          - "com.google.errorprone*"
          - "tech.picnic*"
          - "com.github.spotbugs*"
          - "org.sonarqube*"
          - "net.ltgt*"
      testing:
        patterns:
          - "org.spockframework*"
          - "org.testcontainers*"
          - "io.cucumber*"
          - "io.rest-assured*"
          - "org.wiremock*"
          - "com.icegreen*"
      gradle-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "org.apache.groovy:*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
