version: '3.5'

services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - postgres
    restart: unless-stopped

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - postgres
    ports:
      - "5123:8081"

  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: loans
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  maildev:
    container_name: mail-service
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - postgres
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.11-management-alpine
    environment:
      RABBITMQ_NODENAME: "rabbit@staticrabbit"
    extra_hosts:
      - "staticrabbit:127.0.0.1"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres
    restart: unless-stopped

  vault:
    container_name: vault
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 'super-secret-token'
    cap_add:
      - IPC_LOCK
    volumes:
      - vault:/vault/data
      - vault:/etc/vault/logs
    ports:
      - "8200:8200"
    networks:
      - postgres
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.39.1
    ports:
      - "9090:9090"
    networks:
      - postgres
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:9.2.2
    ports:
      - "3000:3000"
    networks:
      - postgres
    links:
      - prometheus:prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  vault:
