apiVersion: v1
kind: ConfigMap
metadata:
  namespace: loans
  name: rabbitmq
  labels:
    name: rabbitmq
data:
  rabbitmq.conf: |-
    loopback_users.guest = false
    log.console = true
    log.console.level = debug
    log.exchange = true
    log.exchange.level = debug
    management.load_definitions = /etc/rabbitmq/definitions.json
  enabled_plugins: |-
    [rabbitmq_management,rabbitmq_prometheus,rabbitmq_tracing].
  definitions.json: |-
    {
      "queues": [
        {
          "name": "notification.queue",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        }
      ],
      "exchanges": [
        {
          "name": "internal.exchange",
          "vhost": "/",
          "type": "direct",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ],
      "bindings": [
        {
          "source": "internal.exchange",
          "vhost": "/",
          "destination": "notification.queue",
          "destination_type": "queue",
          "routing_key": "internal.notification.routing-key",
          "arguments": {}
        }
      ]
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: loans
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12.2-management-alpine
          ports:
            - containerPort: 15672
              name: http
            - containerPort: 5672
              name: amqp
            - containerPort: 15692
              name: prometheus
          volumeMounts:
            - name: rabbitmq-config-map
              mountPath: /etc/rabbitmq/
      volumes:
        - name: rabbitmq-config-map
          configMap:
            name: rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  namespace: loans
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - port: 15672
      name: http
    - port: 5672
      name: amqp
    - port: 15692
      name: prometheus