server:
  port: 8080

logging:
  file:
    name: logs/back-office.log

spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://localhost:5432/loans
    username: root
    password: root
    hikari.auto-commit: false

  jpa:
    open-in-view: false
    hibernate.ddl-auto: none

  task:
    scheduling:
      thread-name-prefix: cronJob-
      pool:
        size: 3

  cloud:
    openfeign:
      client:
        config:
          risk-checker:
            connect-timeout: 2000
            read-timeout: 5000

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  rabbitmq:
    host: localhost
    connection-timeout: 2s
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  web:
    error:
      include-message: always
      include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true

springdoc:
  show-actuator: true

info:
  application:
    name: Loans Application
    description: Simple loans application
    version: v1.0
  techstack:
    java: Java 25

application:
  timeZone: Europe/Vilnius
  interestRate: 10
  interestIncrementFactor: 1.5
  postponeDays: 7
  activationTokenTtl: P7D

risk:
  checker:
    url: http://localhost:8081

scheduler:
  relayNotificationOutbox:
    enabled: true
    delay: PT5S
    retention: P7D
    purgeCron: "0 0 * * * *"
  evaluateNotEvaluatedLoans:
    enabled: true
    cron: "0 */10 * * * *"
    minAge: PT5M
    batchSize: 100

---
spring:
  config:
    activate:
      on-profile: docker,k8s

logging:
  file:
    name: ""
  structured:
    format:
      console: logstash
    json:
      rename:
        logger_name: class
      add:
        hostname: ${HOSTNAME:}
        app: ${spring.application.name}
        profiles: ${spring.profiles.active:}
