spring:
  datasource:
    url: jdbc:postgresql://postgres.loans.svc.cluster.local:5432/loans
  redis:
    host: redis.loans.svc.cluster.local
  rabbitmq:
    host: rabbitmq.loans.svc.cluster.local

risk:
  checker:
    url: http://risk-checker.loans.svc.cluster.local:8081

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key