spring:
  datasource:
    url: jdbc:postgresql://postgres.loans.svc.cluster.local:5432/loans
  redis:
    host: ${REDIS_HOST:redis.loans.svc.cluster.local}
  rabbitmq:
    host: rabbitmq.loans.svc.cluster.local

risk:
  checker:
    url: http://risk-checker.loans.svc.cluster.local:8081