spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/loans
  redis:
    host: redis
  rabbitmq:
    host: rabbitmq

logging:
  file:
    name: /logs/back-office.log

risk:
  checker:
    url: http://risk-checker:8081