server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/loans
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
#    show-sql: true
    properties:
      #      javax:
      #        persistence:
      #          schema-generation:
      #            create-source: metadata
      #            scripts:
      #              action: create
      #              create-target: create.sql
#      hibernate:
#        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 60000
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

application:
  maxAmount: 100
  interestRate: 10
  interestIncrementFactor: 1.5
  postponeDays: 7
  requestsFromSameIpLimit: 3
  forbiddenHourFrom: 0
  forbiddenHourTo: 6

exceptionMessages:
  clientErrorMessage: Client with id %s does not exist.
  loanErrorMessage: Loan with id %s does not exist.
  riskMessage: Risk is too high, because you are trying to get loan between 00:00 and 6:00 and you want to borrow the max amount!
  amountExceeds: The amount you are trying to borrow exceeds the max amount!
