global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'back_office'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['back-office:8080']
        labels:
          application: 'Back-office Application'