env:
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: AI PR Review

on:
  workflow_dispatch:
  pull_request:

jobs:
  pr_agent_job:
    name: Run pr agent on every pull request, respond to user comments

    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
